sudo: required

services:
    - docker
    - redis-server
    - postgresql

language: python
python:
    - "3.8"

addons:
    postgresql: "9.5"
    apt:
        packages:
        - postgresql-9.5
        - postgresql-client-9.5
        - postgresql-contrib-9.5
        - postgresql-server-dev-9.5
env:
    AG_DB_PASSWORD: ""

install:
    - pip install pip-tools
    - pip-sync requirements.txt requirements-dev.txt
    - python3 generate_secrets.py

before_script:
    - echo $AG_DB_PASSWORD

script:
    pycodestyle autograder &&
    pydocstyle augograder &&
    sh run_mypy.sh &&
    python3 manage.py makemigrations --check &&
    python3 manage.py test -v 2 autograder

# Disabling the schema check so that we can deploy the Django 2.2 revert sooner.
#    python3 manage.py generateschema --generator_class autograder.rest_api.schema.AGSchemaGenerator | diff -q - schema/schema.yml &&
